"""Auditable reporting-level taxonomy. Country-specific census areas stay distinct."""
ALL = ['England', 'Wales', 'Scotland', 'Northern Ireland']
GB = ALL[:3]
EW = ALL[:2]

def level(id, label, group, countries, pattern='', aliases='', note=''):
    return dict(id=id, label=label, group=group, countries=countries,
                pattern=pattern, aliases=aliases.split('|'), note=note)

LEVELS = [
    level('oa-ew','OA · England & Wales','Census',EW,r'(?<!super )output areas?\b|\bOA\b','OA|output area'),
    level('lsoa','LSOA · England & Wales','Census',EW,r'lower[ -]layer super output|\bLSOA\b','LSOA'),
    level('msoa','MSOA · England & Wales','Census',EW,r'middle[ -]layer super output|\bMSOA\b','MSOA'),
    level('oa-sc','OA · Scotland','Census',['Scotland'],aliases='Scottish OA|output area'),
    level('dz-sc','Data Zones · Scotland','Census',['Scotland'],aliases='DZ|data zone'),
    level('iz-sc','Intermediate Zones · Scotland','Census',['Scotland'],aliases='IZ|intermediate zone'),
    level('oa-ni','OA 2001 · Northern Ireland','Census',['Northern Ireland'],aliases='OA|output area'),
    level('sa-ni','Small Areas · Northern Ireland','Census',['Northern Ireland'],aliases='SA|small area'),
    level('soa-ni','Super Output Areas · Northern Ireland','Census',['Northern Ireland'],aliases='SOA|super output area'),
    level('dz-ni','Data Zones · Northern Ireland','Census',['Northern Ireland'],aliases='DZ|data zone'),
    level('sdz-ni','Super Data Zones · Northern Ireland','Census',['Northern Ireland'],aliases='SDZ|super data zone'),
    level('lad','LAD / UA / council areas / LGD','Administration',ALL,r'local authority districts?|\bLAD\b|local government districts?|\bLGD\b','LAD|UA|unitary authority|council area|LGD|metropolitan district|London borough', 'A shared file level: districts, E06 unitary authorities, E08 metropolitan districts, London boroughs, Welsh authorities, Scottish council areas and NI districts are different authority types. A UK or GB file can cover several types.'),
    level('upper','Counties & unitary authorities','Administration',GB,r'counties and unitary authorities|\bCTYUA\b','upper tier|county|CTYUA'),
    level('county','Counties','Administration',['England'],r'(?<!metropolitan )\bcounties\b(?! and)|\bCTY\b','county'),
    level('metro','Metropolitan counties','Administration',['England'],r'metropolitan counties|\bMCTY\b','metropolitan county|West Yorkshire'),
    level('combined','Combined authorities','Administration',['England'],r'combined authorities|\bCAUTH\b','CA|combined authority'),
    level('cca','Combined county authorities','Administration',['England'],r'combined county authorities|\bCCAUTH\b','CCA|combined county authority'),
    level('ward','Electoral wards / divisions','Elections',ALL,r'\bwards?\b|county electoral divisions?|\bWD\b|\bCED\b','ward|electoral division'),
    level('parish','Civil parishes / Welsh communities','Administration',EW,r'\bparishes\b|civil parished|\bPAR\b','parish|community'),
    level('community-sc','Community councils · Scotland','Administration',['Scotland'],aliases='community council'),
    level('dea-ni','District Electoral Areas · NI','Elections',['Northern Ireland'],aliases='DEA|district electoral area'),
    level('westminster','Westminster constituencies','Elections',ALL,r'Westminster parliamentary constituenc|UK parliamentary constituenc|\bPCON\b','constituency|Westminster'),
    level('senedd','Senedd constituencies','Elections',['Wales'],r'(Senedd Cymru|National Assembly for Wales) constituenc|\bNAWCON\b|\bSENC\b','Senedd|Welsh Assembly'),
    level('senedd-region','Senedd electoral regions (historic)','Elections',['Wales'],r'(Senedd Cymru|National Assembly for Wales) electoral regions?|\bNAWER\b','Senedd region'),
    level('scot-parliament','Scottish Parliament constituencies','Elections',['Scotland'],r'Scottish parliamentary constituenc|\bSPC\b','Scottish constituency'),
    level('scot-region','Scottish Parliament regions','Elections',['Scotland'],r'Scottish parliamentary regions?|\bSPR\b','Scottish region'),
    level('ni-assembly','NI Assembly areas','Elections',['Northern Ireland'],aliases='assembly area'),
    level('london-assembly','London Assembly constituencies','Elections',['England'],r'London Assembly constituenc|\bLAC\b','London assembly'),
    level('region','English regions','Regions & countries',['England'],r'(?:^|to )regions?\s*\(|\bRGN\b','region|Government Office Region'),
    level('country','UK countries','Regions & countries',ALL,r'\bcountries\b|\bCTRY\b','country'),
    *[level('itl'+str(n),f'ITL {n}','Regions & countries',ALL,rf'International Territorial Level {n}|\bITL{n}\b',f'ITL {n}') for n in range(1,4)],
    *[level('nuts'+str(n),f'NUTS {n} (historic)','Regions & countries',ALL,rf'NUTS[,]?\s*(?:level )?{n}|\bNUTS{n}\b',f'NUTS {n}') for n in range(1,4)],
    level('lau','Local Administrative Units','Regions & countries',ALL,r'local administrative units?|\bLAU\b','LAU'),
    level('icb','Integrated Care Boards','Health',['England'],r'(?<!sub )integrated care boards?|\bICB\b','ICB'),
    level('sicbl','Sub ICB locations','Health',['England'],r'sub integrated care board|\bSICBL\b','sub ICB'),
    level('ccg','Clinical Commissioning Groups (historic)','Health',['England'],r'clinical commissioning groups?|\bCCG\b','CCG'),
    level('lhb','Local Health Boards · Wales','Health',['Wales'],r'local health boards?|\bLHB\b','LHB|Welsh health board'),
    level('hb-sc','Health boards · Scotland','Health',['Scotland'],aliases='NHS board|health board'),
    level('hsct-ni','Health & Social Care Trusts · NI','Health',['Northern Ireland'],aliases='HSCT|health trust'),
    level('nhs-region','NHS regions / commissioning','Health',['England'],r'NHS (?:England|commissioning|regions)|strategic health authorit|primary care organisations?|\bNHSER\b','NHS region'),
    level('health-other','Public health / cancer / STP areas','Health',['England'],r'public health England|cancer alliance|strategic clinical network|sustainability and transformation|\bSTP\b','STP|cancer alliance|public health'),
    level('bua','Built-up areas','Urban & functional areas',GB,r'built[ -]up areas?\b(?! sub)|urban areas?\b(?! sub)|\bBUA\b','BUA|built up area'),
    level('buasd','Built-up area subdivisions','Urban & functional areas',EW,r'built[ -]up area sub|urban area sub|\bBUASD\b','BUASD'),
    level('settlement-sc','Settlements / localities · Scotland','Urban & functional areas',['Scotland'],aliases='settlement|locality'),
    level('settlement-ni','Settlements · Northern Ireland','Urban & functional areas',['Northern Ireland'],aliases='settlement'),
    level('town','Major towns and cities','Urban & functional areas',EW,r'major towns and cities|\bTCITY\b','town|city'),
    level('fua','Functional urban areas','Urban & functional areas',GB,r'functional urban areas?|\bFUA\b','FUA|metropolitan area'),
    level('urban-audit','Urban Audit cities','Urban & functional areas',GB,r'Urban Audit.*(?:core|greater) cit','Urban Audit|greater city'),
    level('ttwa','Travel-to-work areas','Urban & functional areas',ALL,r'travel to work areas?|\bTTWA\b','TTWA|travel to work'),
    level('workplace','Workplace zones','Urban & functional areas',ALL,r'workplace zones?|\bWZ\b','WZ|workplace zone'),
    level('rural','Urban / rural classifications','Urban & functional areas',ALL,r'urban[ /-]rural|rural[ /-]urban|\bRUC\b','urban rural'),
    level('police','Police force areas','Other reporting areas',EW,r'police force areas?|\bPFA\b','police'),
    level('fire','Fire & rescue authorities','Other reporting areas',EW,r'fire and rescue authorit|\bFRA\b','fire'),
    level('planning','Local planning authorities','Other reporting areas',GB,r'local planning authorit|\bLPA\b','planning authority'),
    level('park','National parks','Other reporting areas',GB,r'national parks?|\bNPARK\b','national park'),
    level('lep','Local Enterprise Partnerships (historic)','Other reporting areas',['England'],r'local enterprise partnerships?|\bLEP\b','LEP'),
    level('other','Other official reporting areas','Other reporting areas',ALL,aliases='registration district|resilience forum|community safety|skills area|postcode'),
]

PROVIDERS = [
    dict(id='ons',name='Office for National Statistics',url='https://geoportal.statistics.gov.uk/',description='UK administrative releases; England and Wales census areas; health, regional and functional geographies; names, codes and lookups.'),
    dict(id='scotgov',name='Scottish Government',url='https://www.gov.scot/collections/small-area-statistics/',description='Data Zones and Intermediate Zones, including 2001, 2011 and 2022 vintages, centroids and matching files.'),
    dict(id='nrs',name='National Records of Scotland',url='https://www.nrscotland.gov.uk/statistics-and-data/geography-products/',description='Scottish census Output Areas, settlements, localities, islands and census linkage files. Older data remains available through official services and the NRS archive.'),
    dict(id='nisra',name='NISRA',url='https://www.nisra.gov.uk/support/geography',description='Northern Ireland OA 2001, Small Areas/SOAs 2011, Data Zones/Super Data Zones 2021 and administrative lookups.'),
    dict(id='osni',name='Ordnance Survey of Northern Ireland',url='https://osni-spatialni.hub.arcgis.com/',description='NI local government, electoral and health services. Source scheme labels are not assumed to be legal commencement dates.'),
    dict(id='wales',name='DataMapWales',url='https://datamap.gov.wales/',description='Welsh communities, Senedd 2026 constituencies and health board definitions. Undated current layers are kept outside annual snapshot cells.'),
    dict(id='os',name='Ordnance Survey Boundary-Line',url='https://osdatahub.os.uk/downloads/open/BoundaryLine',description='Additional GB administrative and electoral files, including GeoPackage downloads. This current product is a source route, not an indexed annual archive.'),
]
